### ISSUE TITLE
Slide Request

### ISSUE THREAD

**Issue by jackieneu** [jastardev/ThatConferenceDataPrivacySlides#1]
Hi Jacob, 
I enjoyed hearing your talk at THAT conference, could you send the slides over? I'm having issues downloading them from the repo. 
Thanks! Jackie

**Comment by jastardev** [comment]
Hey Jackie! Just sent the slides over your way, let me know if you don't get the email. I appreciate you enjoyed the session, look forward to seeing you next year! 
Jacob

**Comment by jackieneu** [comment]
Thanks, I got them!
